- name: Register to the Red Hat Customer Portal by using proxy
  ansible.builtin.include_role:
      name: redhat.rhel_system_roles.rhc
  vars:
    rhc_repositories: "{{ rhsm_enable_repos | default([]) }}"
    rhc_insights:
      state: absent
    rhc_auth:
      login:
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
  when:
  - rhsm_username is defined
  - rhsm_password is defined

- name: Update all installed packages
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Install Satellite package
  become: true
  ansible.builtin.dnf:
    name: 
    - satellite
    - libvirt-client
    - puppet-agent
    state: present