rails_app_satellite_rubygems:
  - rubygem-rails
  - rubygem-pg
  - rubygem-bcrypt
  - rubygem-jwt
  - rubygem-ldap_fluff
  - rubygem-oauth
  - rubygem-redis
  - rubygem-sidekiq
  - rubygem-scoped_search
  - rubygem-will_paginate
  - rubygem-graphql
  - rubygem-dynflow
  - rubygem-rest-client
  - rubygem-audited
  - rubygem-ancestry
  - rubygem-apipie-rails
  - rubygem-apipie-dsl
  - rubygem-rabl
  - rubygem-deep_cloneable
  - rubygem-validates_lengths_from_database
  - rubygem-friendly_id
  - rubygem-secure_headers
  - rubygem-safemode
  - rubygem-fast_gettext
  - rubygem-gettext_i18n_rails
  - rubygem-rails-i18n
  - rubygem-logging
  - rubygem-fog-core
  - rubygem-net-scp
  - rubygem-net-ssh
  - rubygem-net-ping
  - rubygem-activerecord-session_store
  - rubygem-sprockets
  - rubygem-sprockets-rails
  - rubygem-responders
  - rubygem-roadie-rails
  - rubygem-deacon
  - rubygem-sshkey
  - rubygem-daemons
  - rubygem-get_process_mem
  - rubygem-rack-cors
  - rubygem-graphql-batch
  - rubygem-rss
  - rubygem-rexml
  - rubygem-puma
  - rubygem-sinatra
  - postgresql-server
  - postgresql
  - redis
  - nodejs
  - git
  
rails_app_postgresql_module: "postgresql:16"