rhsm_auto_attach: true
rhsm_force_register: false

firewall:
- service: ssh
  zone: public
  state: enabled
  permanent: true
  runtime: true
- service: https
  zone: public
  state: enabled
  permanent: true
  runtime: true
- service: cockpit
  zone: public
  state: enabled
  permanent: true
  runtime: true
- masquerade: true
  zone: public
  state: enabled
  permanent: true
  runtime: true

# Repos to enable after registration, if needed
rhsm_enable_repos: 
- name: rhel-9-for-x86_64-baseos-rpms
  state: enabled
- name: rhel-9-for-x86_64-appstream-rpms
  state: enabled

# Kernel/package checks
expected_kernel_major: "5"
fail_if_not_rhel: true
admin_user: greek_fire
# Virtualization packages for RHEL 9
virtualization_packages:
- lorax
- genisoimage
- pykickstart
- qemu-kvm
- libvirt
- virt-install
- virt-viewer
- virt-manager
- guestfs-tools
- virt-top
- cockpit
- cockpit-machines
- policycoreutils
- policycoreutils-python-utils

libvirt_storage_pool_name: default
libvirt_storage_pool_path: /var/lib/libvirt/images
libvirt_storage_pool_type: dir

nvme_partition:
  disk: /dev/nvme1n1
  number: "4"
  part_start: 112GiB
  part_end: 722GiB 

storage_safe_mode: false
libvirt_storage_pool:
- name: hypervisor
  type: lvm
  disks:
  - /dev/nvme1n1p4
  volumes:
  - name: vm_images
    size: 600 GiB
    fs_type: xfs
    mount_point: /var/lib/libvirt/images
    mount_user: qemu
    mount_group: qemu
    state: present

libvirt_default_network:
- name: 192.168.11.0 
  bridge: virbr11
  dns_servers:
  - 192.168.1.1
  network: 192.168.11.0
  netmask: 255.255.255.0
  gateway: 192.168.11.1
  xml_network_path: /tmp/libvirt-network-11.xml
  xml_content: 
- name: 192.168.111.0 
  bridge: virbr111
  private: true
  network: 192.168.111.0
  netmask: 255.255.255.0
  gateway: 192.168.111.1
  xml_network_path: /tmp/libvirt-network-111.xml

satellite_vm:
  name: satellite
  fqdn: satellite.lab.lou
  ip: 192.168.11.11
  netmask: 255.255.255.0
  gateway: 192.168.11.1
  nameserver: 192.168.11.1
  memory_mb: 20480
  vcpus: 4
  disk_gb: 300
  network: 192.168.11.0
  ks_dir: "{{ libvirt_storage_pool_path }}/kickstarts"
  iso_dir: "{{ libvirt_storage_pool_path }}/boot"
  ks_file: ks.cfg
  ks_iso: satellite-ks.iso
  rhel9_bootiso: "{{ libvirt_storage_pool_path }}/boot/rhel-9.7-x86_64-dvd.iso"

network_connections:
- name: br0
  interface_name: br0
  type: bridge
  state: up
  autoconnect: true
  ip:
    dhcp4: false
    auto6: false
    address:
    - 192.168.11.21/24
    gateway4: 192.168.11.1
    dns: 192.168.11.1
    dns_search: lab.lou
- name: eno1
  interface_name: eno1
  type: ethernet
  controller: br0
  port_type: bridge
  state: up
  autoconnect: true
  ip:
    dhcp4: false
    auto6: false
