- block:
  - name: Stop VM if running
    ansible.builtin.command: "virsh destroy {{ satellite_vm.name }}"
    failed_when: false
    changed_when: false

  - name: Delete VM
    ansible.builtin.command: "virsh undefine {{ satellite_vm.name }} --nvram --remove-all-storage"
  when: 
  - (clean | default(false) | bool) or (clean_vm | default(false) | bool)

- name: Create Satellite VM
  ansible.builtin.command:
    cmd: >-
      virt-install
      --name {{ satellite_vm.name }}
      --memory {{ satellite_vm.memory_mb }}
      --vcpus {{ satellite_vm.vcpus }}
      --disk path=/var/lib/libvirt/images/{{ satellite_vm.name }}.qcow2,size={{ satellite_vm.disk_gb }},format=qcow2
      --network network={{ satellite_vm.network }}
      --cdrom {{ satellite_vm.iso_dir }}/{{ satellite_vm.ks_iso }}
      --location {{ satellite_vm.iso_dir }}/{{ satellite_vm.ks_iso }}
      --extra-args "inst.ks=cdrom:/ks.cfg inst.text"
      --boot uefi
  args:
    creates: "/etc/libvirt/qemu/{{ satellite_vm.name }}.xml"