- name: Ensure Kickstart directory exists
  ansible.builtin.file:
    path: "{{ satellite_vm.ks_dir }}"
    state: directory
    owner: qemu
    group: root
    mode: "0755"

- name: Render Kickstart file
  ansible.builtin.template:
    src: satellite.ks.j2
    dest: "{{ satellite_vm.ks_dir }}/{{ satellite_vm.ks_file }}"
    owner: qemu
    group: root
    mode: "0644"

- name: Validate Kickstart syntax
  ansible.builtin.command:
    cmd: "ksvalidator -v RHEL9 {{ satellite_vm.ks_dir }}/{{ satellite_vm.ks_file }}"
  changed_when: false

- name: Ensure ISO directory exists
  ansible.builtin.file:
    path: "{{ satellite_vm.iso_dir }}"
    state: directory
    owner: qemu
    group: root
    mode: "0755"

- name: Ensure ISO directory are cleaned
  become: true
  ansible.builtin.file:
    path: "{{ satellite_vm.iso_dir }}/{{ satellite_vm.ks_iso }}"
    state: absent
  when: (clean | default(false) | bool)

- name: Build Satellite custom ISO
  ansible.builtin.command:
    cmd: >-
      mkksiso
      {{ satellite_vm.ks_dir }}/{{ satellite_vm.ks_file }}
      {{ satellite_vm.rhel9_bootiso }}
      {{ satellite_vm.iso_dir }}/{{ satellite_vm.ks_iso }}
  args:
    creates: "{{ satellite_vm.iso_dir }}/{{ satellite_vm.ks_iso }}"

- name: Render Kickstart file
  ansible.builtin.template:
    src: satellite.ks.j2
    dest: "{{ satellite_vm.ks_dir }}/{{ satellite_vm.ks_file }}"
    owner: qemu
    group: root
    mode: "0644"
  loop:
  - "{{ satellite_vm.ks_dir }}/{{ satellite_vm.ks_file }}"
  - "{{ satellite_vm.iso_dir }}/{{ satellite_vm.ks_iso }}"