---
- name: Ensure system is RHEL 9
  ansible.builtin.assert:
    that:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "9"
    fail_msg: "This role only supports RHEL 9."

# -----------------------------
# Subscription / CDN
# -----------------------------

- name: Check subscription status
  ansible.builtin.command: subscription-manager status
  register: rhsm_status
  changed_when: false
  failed_when: false

- name: Register to the Red Hat Customer Portal by using proxy
  ansible.builtin.include_role:
      name: redhat.rhel_system_roles.rhc
  vars:
    rhc_repositories: "{{ rhsm_enable_repos | default([]) }}"
    rhc_insights:
      state: absent
    rhc_auth:
      login:
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
  when:
  - rhsm_status.rc != 0
  - rhsm_username is defined
  - rhsm_password is defined

- name: Force refresh subscriptions
  ansible.builtin.command: subscription-manager refresh
  changed_when: false

# -----------------------------
# Kernel Validation
# -----------------------------

- name: Get running kernel
  ansible.builtin.command: uname -r
  register: running_kernel
  changed_when: false

- name: Get default kernel via grubby
  ansible.builtin.command: grubby --default-kernel
  register: default_kernel
  changed_when: false
  failed_when: false

- name: Get installed kernel RPMs
  ansible.builtin.shell: |
    rpm -qa | grep ^kernel
  register: kernel_rpms
  changed_when: false

- name: Debug kernel info
  ansible.builtin.debug:
    msg:
    - "Running kernel: {{ running_kernel.stdout }}"
    - "Default kernel: {{ default_kernel.stdout | default('N/A') }}"
    - "Installed kernels: {{ kernel_rpms.stdout_lines }}"

# -----------------------------
# Install Virtualization Packages
# -----------------------------

- name: Install virtualization stack
  ansible.builtin.dnf:
    name: "{{ virtualization_packages }}"
    state: present

- name: Validate virtualization support
  ansible.builtin.command: virt-host-validate
  register: virt_validate
  changed_when: false
  failed_when: false

- name: Show validation output
  ansible.builtin.debug:
    var: virt_validate.stdout_lines