---

- name: Build list of present users with password data
  no_log: false
  ansible.builtin.set_fact:
    _manage_users_with_passwords: >-
      {{
        manage_users_present
        | selectattr('password_hash', 'defined')
        | list
      }}

- name: Set password for managed users
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password_hash }}"
    update_password: "{{ item.update_password | default('on_create') }}"
  loop: "{{ _manage_users_with_passwords }}"
  loop_control:
    label: "{{ item.username }}"