satellite_compute_resources:
  - name: main.lab.lou
    provider: libvirt
    provider_params:
      url: qemu+ssh://foreman-compute@192.168.11.1/system
      display_type: vnc

satellite_compute_profiles:
- name: 2-Medium
  state: absent
- name: 3-Large
  state: absent
- name: RHEL9
  compute_attributes:
    - compute_resource: main.lab.lou
      vm_attrs:
        cpus: 2
        memory: 8489271296
        nics_attributes:
          0:
            type: network
            network: 192.168.11.0
            model: virtio
        volumes_attributes:
          0:
            pool_name: default
            capacity: 100
            allocation: 0
            format_type: qcow2
