rhsm_enable_repos: 
- name: rhel-9-for-x86_64-baseos-rpms
  state: enabled
- name: rhel-9-for-x86_64-appstream-rpms
  state: enabled
- name: satellite-6.17-for-rhel-9-x86_64-rpms
  state: enabled
- name: satellite-maintenance-6.17-for-rhel-9-x86_64-rpms
  state: enabled

installation_media:
- name: "RHEL 9 BaseOS"
  path: "http://192.168.111.11/pulp/content/hallas/Library/rhel9-kickstart/content/dist/rhel9/9.7/x86_64/baseos/kickstart/"
  state: present
  operatingsystems:
  - Redhat

global_parameters:
- name: root_pass
  value: red22hat
  hidden_value: true
- name: foreman_url
  value: https://192.168.111.11
  hidden_value: no
- name: unattended_url
  value: https://192.168.111.11
  hidden_value: no

safe_mode: false
storage_pools:
- name: rhel
  type: lvm
  disks:
  - /dev/vda3
  volumes:
  - name: pgsql
    type: lvm
    size: 20 GiB
    fs_type: xfs
    mount_point: /var/lib/pgsql
    state: present
  - name: puppetlabs
    type: lvm
    size: 1 GiB
    fs_type: xfs
    mount_point: /opt/puppetlabs
    state: present
  - name: pulp
    type: lvm
    size: 200 GiB
    fs_type: xfs
    mount_point: /var/lib/pulp
    state: present