ipaadmin_password: "{{ idmadmin_password }}"
rhsm_enable_repos: 
- name: rhel-9-for-x86_64-baseos-rpms
  state: enabled
- name: rhel-9-for-x86_64-appstream-rpms
  state: enabled
- name: satellite-6.17-for-rhel-9-x86_64-rpms
  state: enabled
- name: satellite-maintenance-6.17-for-rhel-9-x86_64-rpms
  state: enabled

rhc_repositories: "{{ rhsm_enable_repos | default([]) }}"
rhc_insights:
  state: absent
rhc_auth:
  login:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"

settings:
- name: foreman_url
  value: https://satellite.lab.lou
  hidden_value: no
- name: unattended_url
  value: http://satellite.lab.lou
- name: destroy_vm_on_host_delete
  value: true
  field_type: boolean

global_parameters:
- name: loader_timeout
  value: 1

timesync_ntp_provider: chrony
timesync_ntp_servers:
  - hostname: 192.168.11.21
    iburst: true

safe_mode: false
storage_pools:
- name: rhel
  type: lvm
  disks:
  - /dev/vda3
  volumes:
  - name: pgsql
    type: lvm
    size: 20 GiB
    fs_type: xfs
    mount_point: /var/lib/pgsql
    state: present
  - name: puppetlabs
    type: lvm
    size: 1 GiB
    fs_type: xfs
    mount_point: /opt/puppetlabs
    state: present
  - name: pulp
    type: lvm
    size: 200 GiB
    fs_type: xfs
    mount_point: /var/lib/pulp
    state: present