satellite_manifest_download: true
satellite_rhsm_username: "{{ rhsm_username }}"
satellite_rhsm_password: "{{ rhsm_password }}"
satellite_manifest_uuid: "a47b22fb-7af0-4e68-b092-659b87e2fa8e"
satellite_manifest_path: "~/manifest.zip"