satellite_architectures:
- name: "x86_64"
  operating_systems:
  - "RHEL-KS"
satellite_operatingsystems:
- name: "RHEL-KS"
  major: "9"
  minor: "7"
  os_family: "Redhat"
  password_hash: "SHA256"
  provisioning_templates:
  - "Kickstart default"
  - "Kickstart default finish"
  - "Kickstart oVirt-RHVH PXELinux"
  - "Kickstart default PXEGrub2"
  ptables:
  - Compliance STIG Virtual
  default_templates:
  - template_kind: "finish"
    provisioning_template: "Kickstart default finish"
  - template_kind: "provision"
    provisioning_template: "Kickstart default"
  - template_kind: PXELinux
    provisioning_template: "Kickstart oVirt-RHVH PXELinux"
  - template_kind: PXEGrub2
    provisioning_template: Kickstart default PXEGrub2
