- name: Ensure TLS private key directory exists
  ansible.builtin.file:
    path: "{{ argus_cert_path }}/private"
    state: directory
    owner: root
    group: "{{ argus_group }}"
    mode: "0700"

- name: Ensure TLS cert directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ argus_cert_path }}/cert"
    owner: root
    group: "{{ argus_group }}" 
    mode: "0750"

- name: Create self-signed Argus TLS certificate for dev
  ansible.builtin.command:
    cmd: >
      openssl req -x509 -newkey rsa:4096 -sha256 -days 365
      -nodes
      -keyout {{ argus_tls_key }}
      -out {{ argus_tls_cert }}
      -subj "/CN={{ argus_fqdn }}"
      -addext "subjectAltName=DNS:{{ argus_fqdn }}"
  args:
    creates: "{{ argus_tls_cert }}"

- name: Set Argus TLS private key permissions
  ansible.builtin.file:
    path: "{{ argus_tls_key }}"
    owner: root
    group: "{{ argus_group }}"
    mode: "0600"

- name: Set Argus TLS certificate permissions
  ansible.builtin.file:
    path: "{{ argus_tls_cert }}"
    owner: root
    group: "{{ argus_group }}"
    mode: "0640"