- name: Configure Puma
  ansible.builtin.template:
    src: puma.rb.j2
    dest: "{{ argus_home_path }}/config/puma.rb"
    owner: "{{ argus_user }}"
    group: "{{ argus_group }}"
    mode: "0640"
  notify: Restart Argus 

- name: Configure Argus systemd service
  ansible.builtin.template:
    src: argus.service.j2
    dest: /etc/systemd/system/argus.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Argus
- include_tasks: certs.yml
- include_tasks: httpd.yml
