- name: Enable and start Redis
  ansible.builtin.systemd:
    name: redis 
    enabled: true
    state: started
    daemon_reload: true

- name: Enable and start Argus
  ansible.builtin.systemd:
    name: argus
    enabled: true
    state: started
    daemon_reload: true

- name: Enable and start httpd
  ansible.builtin.systemd:
    name: httpd
    enabled: true
    state: started
    daemon_reload: true