- name: "Add Installation Media"
  redhat.satellite.installation_medium:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organizations: "{{ item.organization | default([satellite_organization]) }}"
    locations: "{{ item.location | default([satellite_location]) }}"
    name: "{{ item.name | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    use_gssapi: "{{ item.use_gssapi | default(omit) }}"
    os_family: "{{ item.os_family | default(omit) }}"
    updated_name: "{{ item.updated_name | default(omit) }}"    
    operatingsystems: "{{ item.operatingsystems | default(omit) }}"
  loop: "{{ installation_media }}"