name: Upload subscription manifest
redhat.satellite.subscription_manifest:
  username: "{{ satellite_username }}"
  password: "{{ satellite_password }}"
  server_url: "{{ satellite_server_url }}"
  validate_certs: "{{ satellite_validate_certs }}"
  organization: "{{ satellite_organization }}"
  manifest_path: "{{ satellite_manifest_path }}"
  state: present