- include_role:
    name: redhat.satellite.manifest
  when: setup_manifest | bool

- name: "Set a Setting"
  redhat.satellite.setting:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ settings }}"
  tags:
  - settings
  - hostgroups

- include_role:
    name: redhat.satellite.repositories
    apply:
      tags: 
      - products
  when: 
  - satellite_products | length > 0
  tags:
  - products

- include_tasks: 
    file: global_parameter.yml
    apply:
      tags: 
      - global_parameters
      - hostgroups
  when: 
  - global_parameters | length > 0
  tags:
  - hostgroups
  - global_parameters  

- include_tasks: 
    file: installation_medium.yml
    apply:
      tags: 
      - installation_medium
      - hostgroups
  when: 
  - installation_media | length > 0
  tags:
  - hostgroups
  - installation_medium  

- include_tasks: 
    file: async_product_sync.yml
    apply:
      tags: 
      - sync_repositories
  when: 
  - satellite_products | length > 0
  tags:
  - sync_repositories  

- include_role:
    name: redhat.satellite.compute_resources
    apply:
      tags: 
      - compute_resources
      - compute_profiles
      - hostgroups
  when: 
  - satellite_compute_resources | length > 0
  tags: 
  - compute_resources
  - compute_profiles
  - hostgroups

- include_role:
    name: redhat.satellite.compute_profiles
    apply:
      tags: 
      - compute_profiles
      - hostgroups
  when: 
  - satellite_compute_profiles | length > 0
  tags: 
  - compute_profiles
  - hostgroups

- include_role:
    name: redhat.satellite.content_views
    apply:
      tags: 
      - content_views
      - hostgroups
  when: 
  - satellite_content_views | length > 0
  tags:
  - content_views
  - hostgroups

- include_tasks: 
    file: async_publish_content_view.yml
    apply:
      tags:
      - sync_content_views
  when: 
  - satellite_content_views | length > 0

- include_role:
    name: redhat.satellite.domains
    apply:
      tags: 
      - domains
      - hostgroups
  when:
  - satellite_domains | length > 0
  tags:
  - hostgroups
  - domains

- include_role:
    name: redhat.satellite.subnets
    apply:
      tags: 
      - subnets
      - domains
      - hostgroups
  when:
  - satellite_subnets | length > 0
  tags: 
  - domains
  - subnets

- include_tasks: 
    file: satellite_partition_tables.yml
    apply:
      tags: 
      - partition_tables
      - hostgroups
  when:
  - satellite_partition_tables | length > 0
  tags: 
  - partition_tables
  - hostgroups

- include_role:
    name: redhat.satellite.operatingsystems
    apply:
      tags: 
      - os
      - hostgroups
  when:
  - satellite_operatingsystems | length > 0
  tags: 
  - os
  - hostgroups

- include_tasks: 
    file: satellite_architectures.yml
    apply:
      tags: 
      - os
      - architecture
      - hostgroups
  when:
  - satellite_architectures | length > 0
  tags: 
  - architecture
  - os
  - hostgroups

- include_role:
    name: redhat.satellite.hostgroups
    apply:
      tags: hostgroups
  when:
  - satellite_hostgroups| length > 0
  tags: hostgroups