- name: "Add Partition Tables"
  redhat.satellite.partition_table:
    username: "{{ satellite_username | default(omit) }}"
    password: "{{ satellite_password | default(omit) }}"
    server_url: "{{ satellite_server_url | default(omit) }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organizations: "{{ item.organization | default([satellite_organization]) }}"
    locations: "{{ item.location | default([satellite_location]) }}"
    file_name: "{{ item.name | default(omit) }}"
    layout: "{{ item.layout }}"
    state: "{{ item.state | default('present') }}"
    os_family: "{{ item.os_family | default(omit) }}"
    updated_name: "{{ item.updated_name | default(omit) }}"
    locked: "{{ item.locked | default(omit) }}"
  loop: "{{ satellite_partition_tables }}"